name: Build React app to Azure Web App

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: mozart-front
  AZURE_WEBAPP_PACKAGE_PATH: "."
  NODE_VERSION: "14.x"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        run: |
          yarn install
      - name: Linting the code
        run: |
          yarn lint
      - name: Format code
        run: |
          yarn run prettier --write ./src/**/*.{ts, tsx} ./src/**/**/*.{ts, tsx}
      - name: Build React app
        run: |
          yarn build
      - name: add process.json
        run: |
          echo '{ "script": "serve", env: { "PM2_SERVE_SPA": "true", "PM2_SERVE_HOMEPAGE": "/index.html" } }' >> build/process.json
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: build
